export enum ActionType {
  GET_ALL = "GET_ALL",
  SEARCH_CRYPTO = "SEARCH_CRYPTO",
  SAVE_CRYPTO = "SAVE_CRYPTO",
  DELETE_CRYPTO = "DELETE_CRYPTO",
  UPDATE_USER_CRYPTO = "UPDATE_USER_CRYPTO",
  LOAD_USER_CRYPTO = "LOAD_USER_CRYPTO"
}